# Generated by Django 3.2.6 on 2021-08-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='video_summary_link',
        ),
        migrations.AddField(
            model_name='summary',
            name='blob',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='summary',
            name='summaries',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='summary',
            name='questions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='summary',
            name='related_tags',
            field=models.TextField(default=''),
        ),
    ]
